[package]
name = "test/custom-node"
version = "0.1.0"
description = "Custom node bridge package"

[dependencies]
"sharrattj/coreutils" = "1.0.16"

[[module]]
name = "node-bridge"
source = "node-bridge.wasm"
abi = "wasi"

[[command]]
name = "node"
module = "node-bridge"
runner = "wasi"

[fs]
"/scripts" = "./scripts"
